// Generated by scripts/generate-dom-source-ast.mjs. Do not edit.
'use client';

import { useState } from 'react';
import styles from '../_components/demo.module.scss';
function StatusBadge({
  children
}: {
  children: string;
}) {
  return <span className={styles.astBadge} data-source-id="ast_0d8fc112f2">{children}</span>;
}
export function AstFixture() {
  const [items, setItems] = useState(['Parser']);
  return <div className={styles.fixture} data-source-id="ast_6c8f7846cb">
      <section className={styles.astHero} data-source-id="ast_da51d15eab">
        <StatusBadge>COMPILE-TIME IDENTITY</StatusBadge>
        <h2 data-source-id="ast_77e4b5c037">源码位置由 AST 自动采集。</h2>
        <p data-source-id="ast_a2656641c1">DOM 只携带短节点 ID，完整文件位置保存在独立映射表中。</p>
        <div className={styles.astFlow} data-source-id="ast_3b3136071d">
          <span data-source-id="ast_e8a26104d1">TSX</span><i data-source-id="ast_b160a37290">→</i><span data-source-id="ast_44558d95f9">AST</span><i data-source-id="ast_3c429548ee">→</i><span data-source-id="ast_54a145074e">DOM</span><i data-source-id="ast_6c7a388cc1">→</i><span data-source-id="ast_f6641f5634">SOURCE</span>
        </div>
      </section>

      <div className={styles.fixtureGrid} data-source-id="ast_b1765b4ee1">
        <article className={styles.astCodeCard} data-source-id="ast_db225b69ab">
          <span data-source-id="ast_d1c914c6a3">AUTOMATIC INJECTION</span>
          <pre data-source-id="ast_6c67a041df"><code data-source-id="ast_b1c995d177">{'<button data-source-id="ast_…">'}</code></pre>
          <p data-source-id="ast_7a2cdfd1c7">修改源码行数后重新生成，映射表会自动更新。</p>
        </article>

        <article className={styles.astSvgCard} data-source-id="ast_e55f3d0a09">
          <svg viewBox="0 0 240 120" role="img" aria-label="AST 节点关系图" data-source-id="ast_b5a9af053d">
            <path d="M20 88 C 62 12, 98 104, 140 36 S 190 18, 220 62" fill="none" stroke="currentColor" strokeWidth="7" strokeLinecap="round" data-source-id="ast_2b92f81913" />
            <circle cx="140" cy="36" r="10" data-source-id="ast_98b2d945f5" />
          </svg>
          <div data-source-id="ast_7a5bd092f7">
            <span data-source-id="ast_482d019765">SVG HOST NODES</span>
            <h3 data-source-id="ast_eac6b5a6bf">宿主节点分别映射</h3>
            <p data-source-id="ast_85814ed2dd">选择 SVG、path 或 circle，可以定位到各自的 JSX AST 节点。</p>
          </div>
        </article>
      </div>

      <section className={styles.dynamicSection} data-source-id="ast_c2046aa541">
        <div data-source-id="ast_fe0f4bef7a">
          <span data-source-id="ast_b29e64fda1">REPEATED RENDERING</span>
          <h3 data-source-id="ast_b443b5ae5e">同一个 AST 节点，多次渲染</h3>
        </div>
        <button type="button" onClick={() => setItems(current => [...current, `Node ${current.length + 1}`])} data-source-id="ast_b1ed9b5fc5">
          添加实例
        </button>
        <div className={styles.instanceList} data-source-id="ast_6ac7a590ea">
          {items.map((item, index) => <div key={`${item}-${index}`} data-source-id="ast_3cf2e550df">
              <span data-source-id="ast_8fbe2c6250">{String(index + 1).padStart(2, '0')}</span>
              <strong data-source-id="ast_9d921dfaf1">{item}</strong>
            </div>)}
        </div>
      </section>
    </div>;
}
